AllCops:
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.5

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent
  IndentationWidth: 2

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/AbcSize:
  Max: 65
  Exclude:
    - 'db/migrate/*'

Metrics/BlockLength:
  Max: 60
  Exclude:
    - 'config/routes.rb'
    - 'lib/tasks/**/*'

Metrics/ClassLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 200
  Exclude:
    - 'db/migrate/*'

Metrics/MethodLength:
  Max: 60
  Exclude:
    - 'db/migrate/*'

Metrics/ModuleLength:
  Max: 300

Metrics/PerceivedComplexity:
  Max: 10

Style/ClassAndModuleChildren:
  AutoCorrect: true

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/GuardClause:
  MinBodyLength: 3

Style/IfUnlessModifier:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/*'

Style/MultipleComparison:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SafeNavigation:
  Exclude:
    - 'bin/cable'

Style/SymbolArray:
  MinSize: 7
